### ISSUE TITLE
Implementing kinetics for a specific third body collider

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1070]
The BurkeH2O2inN2 library has a case where a third body reaction has a specific implementation for `Ar` (and `He`) as a third body collider:
```
entry(
    index = 5,
    label = "H2 <=> H + H",
    degeneracy = 1,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(A=(4.577e+19, 'cm^3/(mol*s)'), n=-1.40, Ea=(104380, 'cal/mol'), T0 = (1, 'K')),
        efficiencies = {'[H][H]': 2.5, 'O': 12, '[C-]#[O+]': 1.9, 'O=C=O': 3.8, '[Ar]': 0, '[He]': 0},
    ),
    shortDesc = u"""Tsang and Hampson, J. Phys. Chem. Ref. Data, 15:1087 (1986)""",
)

entry(
    index = 6,
    label = "H2 + Ar <=> H + H + Ar",
    degeneracy = 1,
    kinetics = Arrhenius(A=(5.84e+18, 'cm^3/(mol*s)'), n=-1.10, Ea=(104380, 'cal/mol'), T0 = (1, 'K')),
    shortDesc = u"""Tsang and Hampson, J. Phys. Chem. Ref. Data, 15:1087 (1986)""",
)
```

which is transformed into the following Chemkin reactions:
```
H2(1)+M=H(2)+H(2)+M                                 4.577e+19 -1.400    104.380  
H2(1)/2.50/ Ar/0.00/ 


Ar+H2(1)=H(2)+H(2)+Ar                               5.840e+18 -1.100    104.380  
```

However, a similar implementation in which the reaction for the specific collider is given in a pressure dependence form isn't treated well in RMG. Conside `SO2+O<=>SO3` for example (taken from the SOxNOx library, currently on the sulfur branch):
```
entry(
    index = 225,
    label = "SO2 + O <=> SO3",
    degeneracy = 1,
    kinetics = Troe(
        arrheniusHigh = Arrhenius(A=(3.7e+11, 'cm^3/(mol*s)'), n=0, Ea=(1689, 'cal/mol'), T0=(1, 'K')),
        arrheniusLow = Arrhenius(A=(2.4e+27, 'cm^6/(mol^2*s)'), n=-3.6, Ea=(5186, 'cal/mol'), T0=(1, 'K')),
        alpha = 0.442, T3=(316, 'K'), T1=(7442, 'K'), efficiencies={'O=S=O': 10, 'O': 10, 'O=C=O': 2.5, 'N#N': 0}),
    shortDesc = u"""[Marshall2005],[Marshall2006]""",
    longDesc =
u"""
Calculated for Ar as the main bath gas
""",
)

entry(
    index = 226,
    label = "SO2 + O + N2 <=> SO3 + N2",
    degeneracy = 1,
    kinetics = Troe(
        arrheniusHigh = Arrhenius(A=(3.7e+11, 'cm^6/(mol^2*s)'), n=0, Ea=(1689, 'cal/mol'), T0=(1, 'K')),
        arrheniusLow = Arrhenius(A=(2.9e+27, 'cm^9/(mol^3*s)'), n=-3.58, Ea=(5206, 'cal/mol'), T0=(1, 'K')),
        alpha=0.43, T3=(371, 'K'), T1=(7442, 'K'), efficiencies={}),
    shortDesc = u"""[Marshall2005],[Marshall2006]""",
    longDesc =
u"""
Complementary to the reaction above for N2 as the main bath gas
""",
)
```

These reactions are transformed into the following Chemkin format:
```
O(3)+SO2(1)(+M)=SO3(2)(+M)                          3.700e+11 0.000     1.689    
SO2(1)/10.00/ N2(4)/0.00/ 
    LOW/ 2.400e+27 -3.600    5.186    /
    TROE/ 4.420e-01 316       7.44e+03 /


O(3)+N2(4)+SO2(1)(+M)=SO3(2)+N2(4)(+M)              3.700e+11 0.000     1.689    
    LOW/ 2.900e+27 -3.580    5.206    /
    TROE/ 4.300e-01 371       7.44e+03 /
```

The problem is that the last reaction now has 4 reactants (including the `(+M)`), considering two colliders (and thus reducing the rate).
In my understanding, the reaction string should be something like: `O(3)+SO2(1)(+N2(4))=SO3(2)+(+N2(4))`
But this introduces a new problem of double parenthesis `(+N2(4))`, which confuses Chemkin:
```Error identifying pres-dependency 3rd body reactant...(+N2(4)
      Error identifying pres-dependency 3rd body product...(+N2(4)
      Error...did not find pres-dependency reactant...
      Error...did not find pres-dependency product...
      Error...undeclared species...O(3))
      Error...undeclared species...SO3(2))
      Low pressure limit:  0.29000E+28 -0.35800E+01  0.52060E+01
      TROE centering:      0.43000E+00  0.37100E+03  0.74400E+04
      Error...reaction does not balance in elements/mass...
```

A reaction of this sort `O(3)+SO2(1)(+N2)=SO3(2)+(+N2)` does pass Chemkin's pre-processor.

I think RMG should have a specific keyword for specifying only a certain collider.
And, if the keyword is encountered, should the colliding species be renamed to drop the parenthesis?
(or is there a simpler implementation I am unaware of?)

**Comment by rwest** [comment]
Specific third body colliders have been on my wish list for a while. It's not just an inability to translate into (or from) CHEMKIN, but RMG currently cannot internally represent these reactions. Eg:
H+H(+Ar)<=>H2(+Ar)

One could do it as 
H+H(+M)<=>H2(+M)
With an infinitely long list of collision efficiencies  (everything except Ar) set to zero.

So RMG needs some work.  
The problem of species names including parenthesis hadn't even occurred to me, but is yet another problem for CHEMKIN compatibility. Only solution is to rename. 
Could do `N2_4` instead of `N2(4)` I suppose.

**Comment by rwest** [comment]
One check: your reaction string has to many plus signs.  Did you try 
`O(3)+SO2(1)(+N2(4))=SO3(2)(+N2(4))`
In CHEMKIN?

**Comment by alongd** [comment]
Right, the additional `+` is my typo, sorry.

running the (correct) double parenthesis reaction in Chemkin's pre-processor gives:
```
  72. SO2(3)+O(9)(+N2(4))=SO3(16)(+N2(4))            3.70E+11    0.0        1.7
      Error identifying pres-dependency 3rd body reactant...(+N2(4)
      Error identifying pres-dependency 3rd body product...(+N2(4)
      Error...did not find pres-dependency reactant...
      Error...did not find pres-dependency product...
      Error...undeclared species...O(9))
      Error...undeclared species...SO3(16))
      Low pressure limit:  0.29000E+28 -0.35800E+01  0.52060E+01
      TROE centering:      0.43000E+00  0.37100E+03  0.74400E+04
      Error...reaction does not balance in elements/mass...
```

**Comment by rwest** [comment]
File a bug report with CHEMKIN? (Does their manual say species names must not contain parentheses?)
Can Cantera (and ck2cti) cope?

**Comment by alongd** [comment]
The Chemkin manual (Table 3-2) does not refer to parenthesis in species names.
```
Species names are composed of up to 16-character upper- or lower- case
symbols. The names cannot begin with the characters +, =, or a number; an
ionic species name may end with one or more +'s or -'s.
```

ck2cti could not import this syntax.
It gave the following error of duplicate reactions, although I also tried running with this reaction only in the Chemkin file:
```
Encountered unmarked duplicate reaction CH3(15) + CH2NH2(26) (+ H2O(8)) <=> NCC(3) (+ H2O(8))
```

**Comment by alongd** [comment]
Cantera also threw an error for a specific third body collider with parenthesis in its name. In this case, `H2(7)` was used as the specific collider:
```
CanteraError: 
***********************************************************************
CanteraError thrown by ct2ctml_string:
Error converting input file "mechs/x-test.cti" to CTML.
Python command was: '/home/alongd/anaconda2/envs/rmg_env/bin/python'
The exit code was: 1
-------------- start of converter log --------------
***** Error parsing input file *****


species H2(7)) not found

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/home/alongd/anaconda2/envs/rmg_env/lib/python2.7/site-packages/cantera/ctml_writer.py", line 2658, in convert
    write(outName)
  File "/home/alongd/anaconda2/envs/rmg_env/lib/python2.7/site-packages/cantera/ctml_writer.py", line 374, in write
    rx.build(r)
  File "/home/alongd/anaconda2/envs/rmg_env/lib/python2.7/site-packages/cantera/ctml_writer.py", line 1579, in build
    r = reaction.build(self, p)
  File "/home/alongd/anaconda2/envs/rmg_env/lib/python2.7/site-packages/cantera/ctml_writer.py", line 1218, in build
    raise CTI_Error("species "+s+" not found")
cantera.ctml_writer.CTI_Error
--------------- end of converter log ---------------
***********************************************************************
```

I sent an email to Chemkin describing this bug. While we could also patch Cantera for this, I think that @rwest's suggestion to rename a specific collider as `H2_7` instead of `H2(7)`, for example, is simpler.

**Comment by alongd** [comment]
Regarding the implementation in libraries we of course cannot write `label = "SO2 + O + N2 <=> SO3 + N2",` since here `N2` is a normal reactant/product, and RMG ends up adding a `(+M)`.
Perhaps the library should be written as:
```
entry(
    index = 226,
    label = "SO2 + O <=> SO3",
    specificCollider= "N2",
    ...
```
Adding a keyword like `specificCollider`, directing RMG to add `(+N2)` instead, and changing N2's label as discussed above to remove the parenthesis.

By the way, what's the difference between `+M` and `(+M)`?
I see the first in reactions with no specific PDep form (such as CHEB, PLOG, TROE) other than the concentration of the bath gas, e.g.:
```
H2O+M=H+OH+M                              6.064e+27 -3.322    120.790  
H2O/0.00/ H2/3.00/ O2/1.50/ N2/2.00/ 
```

**Comment by rwest** [comment]
Just like `H + H =>` would always be a two-body reaction with second order rate and a rate coefficient in units of cm3/mol/s (or equivalent),
`H + H + M =>` would  would always be a three-body reaction with third order rate and a rate coefficient in units of cm6/mol2/s (or equivalent).
`H + H (+M) =>` indicates the pressure-dependence, where it's a three-body reaction with third order rate at low pressures (low concentrations of `M`), and a two-body reaction with second order rate at high pressures (high concentrations of `M`). You must provide both expressions, high and low, or some other pressure-dependent form (PLog, Chebyshev). In general the `M` can be anything, equally weighted, but if it has a line like `H2O/0.00/ H2/3.00/ O2/1.50/ N2/2.00/` following, that indicates that the collision efficiencies of certain species; in this case N2 counts double when evaluating the concentration of `M` and H2O does not count at all - probably because it's described in a different reaction, like follows...

`H + H (+H2O) =>` indicates the same thing but only H2O can count as the collider. This is needed when there isn't just a linear scaling relative to the other colliders, but perhaps a different temperature-dependence, for example. 

I'm sure there are more details somewhere like the chemkin manual.

Your proposal of how to store it is pretty good.

**Comment by rwest** [comment]
It seems that species names with parentheses cause problems for both chemkin and cantera.
I understand that @alongd has opened an issue with ansys to fix chemkin, and I have opened this one for cantera: https://github.com/Cantera/cantera/pull/460 (please feel free to add a fix!).

In the mean time (it'll no doubt be a while before the whole world is using the bug-fixed versions) I guess we'll have to rename things that end up being used as explicit third-body colliders (if not everything).

**Comment by goldmanm** [comment]
What do y'all think about replacing the parenthesis in RMG's naming with a dash, which I think fits [chemkin requirements](http://www.fkm.utm.my/~mohsin/sme4483/chemical.kinetics/chemkin.format.pdf) This would also free up another character we can use to name the species.

For example:

C3H5O2(1052) becomes C3H5O2-1052
S(33000) becomes S-33000

Any thoughts, suggestions other ideas? We could also use `_` instead of `-`? Seems like we would be modifying `rmgpy.chemkin.getSpeciesIdentifier` to prevent any parenthesis and also fix current formatting

**Comment by rwest** [comment]
Dash sounds ok to me.

**Comment by alongd** [comment]
Ansys / Reaction Design fixed the parenthesis issue, the fix will be included in the upcoming release.
(Case Number: 23852, fix: DE153361)

**Comment by rwest** [comment]
Also now fixed in Cantera: https://github.com/Cantera/cantera/pull/460

**Comment by goldmanm** [comment]
So it seems like the need to change RMG naming is gone, but how we represent third body colliders is still an issue, correct?

**Comment by alongd** [comment]
We might still want to change the naming for back compatibility with the current or older Chemkin versions. However, this is not pressing, since a specific collider in a PDep reaction (unlike the Burke libraries) isn't really ubiquitous.
You are right, the parenthesis naming was a side issue here (although important). The focus is on getting RMG to properly read/write and handle specific colliders.
All of this is already implemented, I'll PR it soon. I'm just having trouble with the solver (simple.pyx): I though I made the necessary additions to it, but one new test is still failing. I'll open the PR soon, and would love any help and another pair of eyes looking at it.

**Comment by alongd** [comment]
Should be fixed by #1084.
