### ISSUE TITLE
AttributeError: 'rmgpy.kinetics.arrhenius.MultiArrhenius' object has no attribute 'T0

### ISSUE THREAD

**Issue by AH9316** [ReactionMechanismGenerator/RMG-Py#1652]
### Topic
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [x] An error message 

### Context
When we run a case on service we get an error message, which is "AttributeError: 'rmgpy.kinetics.arrhenius.MultiArrhenius' object has no attribute 'T0'".

I attach the files we get below
[26_RR_0.01_T_0.01.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3388183/26_RR_0.01_T_0.01.zip)

It includes input file, RMG.log and slurm.out file. 

### Question
Even though we meet this error, we still get a chem.inp. Does this error important and how will this error affect the chem.inp?

**Comment by mjohnson541** [comment]
The mechanism terminated properly and should be fine.  It seems that the collision limit analysis functions can't handle all of the data formats RMG supports.

**Comment by mliu49** [comment]
Fixed by #1659

**Comment by AH9316** [comment]
@mliu49 Hi Max. I use the basic user version RMG and I used "conda upadate rmg rmgdatabase -c rmg" to upadate my RMG. However, when I run the cases I still get this error and the RMG.log shows me that my RMG is still version 2.4.0. Is version 2.4.1 only available for the developer version?

**Comment by mliu49** [comment]
Binary versions of 2.4.1 are available for Linux and MacOS. If conda update isn't working, you can try explicitly installing it using `conda install rmg=2.4.1 -c rmg`. Either way, you should confirm the version using `conda list rmg` or `python -c "import rmgpy; print rmgpy.__version__"`.
