### ISSUE TITLE
Redundant Species in a Reaction Mechanism

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/RMG-Py#831]
I have encountered a strange error where the core contains multiple copies of the same species. The species are all polycyclic aromatic radicals and the error seems to only occur when the saturated version of these species are included in a thermodynamic library (adding the saturated species to a thermo library seemed to trigger the problem).

Consider these consecutive "enlarge" steps recorded in the RMG.log file.

Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 8 new edge species
    [CH] (Cc1ccccc1)c1ccccc1(11694)
    [c]1ccccc1CCc1ccccc1(11695)
    [c]1ccc(cc1)CCc1ccccc1(11696)
    [c]1cccc(c1)CCc1ccccc1(11697)
    [CH] (SCc1ccccc1)c1ccccc1(11698)
    [c]1ccccc1CSCc1ccccc1(11699)
    [c]1cccc(c1)CSCc1ccccc1(11700)
    [c]1ccc(cc1)CSCc1ccccc1(11701)
Added 0 new core reactions
Created 8 new edge reactions
    [CH] (Cc1ccccc1)c1ccccc1(11694) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1ccccc1CCc1ccccc1(11695) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1ccc(cc1)CCc1ccccc1(11696) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1cccc(c1)CCc1ccccc1(11697) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH](SCc1ccccc1)c1ccccc1(11698) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1ccccc1CSCc1ccccc1(11699) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1cccc(c1)CSCc1ccccc1(11700) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1ccc(cc1)CSCc1ccccc1(11701) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)

After model enlargement:
    The model core has 398 species and 6766 reactions
    The model edge has 11307 species and 43274 reactions

Saving current model core to Chemkin file...
Chemkin file contains 6766 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 6766 reactions.
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 01:20:07:34
    Memory used: 1658.88 MB

Conducting simulation of reaction system 1...
At time 1.0000e-01 s, species [CH] (SCc1ccccc1)c1ccccc1(11562) exceeded the minimum rate for moving to model core
    Characteristic rate: 8.0216e+03 mol/m^3*s
    [CH](SCc1ccccc1)c1ccccc1(11562) rate: 8.1141e+02 mol/m^3*s (0.1012)
    DBDS(1) conversion: 0.5313
At time 1.0000e-01 s, species [CH] (SCc1ccccc1)c1ccccc1(11562) exceeded the minimum rate for simulation interruption
    Characteristic rate: 8.0216e+03 mol/m^3*s
    [CH] (SCc1ccccc1)c1ccccc1(11562) rate: 8.1141e+02 mol/m^3*s (0.1012)
    DBDS(1) conversion: 0.5313

Adding species [CH] (SCc1ccccc1)c1ccccc1(11562) to model core
Generating kinetics for new reactions...

Summary of Model Enlargement
---------------------------------
Added 1 new core species
    [CH] (SCc1ccccc1)c1ccccc1(11562)
Created 0 new edge species
Moved 1 reactions from edge to core
    [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH] (SCc1ccccc1)c1ccccc1(11562) + c1ccc(cc1)CSCc1ccccc1(34)
Added 0 new core reactions
Created 0 new edge reactions

After model enlargement:
    The model core has 399 species and 6767 reactions
    The model edge has 11306 species and 43273 reactions

At time 1.0646e+00 s, reached target termination conversion: 0.800000 of DBDS(1)
    DBDS(1) conversion: 0.8

Generating kinetics for new reactions...

Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 8 new edge species
    [CH](Cc1ccccc1)c1ccccc1(11702)
    [c]1ccccc1CCc1ccccc1(11703)
    [c]1ccc(cc1)CCc1ccccc1(11704)
    [c]1cccc(c1)CCc1ccccc1(11705)
    [CH](SCc1ccccc1)c1ccccc1(11706)
    [c]1ccccc1CSCc1ccccc1(11707)
    [c]1cccc(c1)CSCc1ccccc1(11708)
    [c]1ccc(cc1)CSCc1ccccc1(11709)
Added 0 new core reactions
Created 8 new edge reactions
    [CH](Cc1ccccc1)c1ccccc1(11702) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1ccccc1CCc1ccccc1(11703) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1ccc(cc1)CCc1ccccc1(11704) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [c]1cccc(c1)CCc1ccccc1(11705) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CCc1ccccc1(76)
    [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH](SCc1ccccc1)c1ccccc1(11706) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1ccccc1CSCc1ccccc1(11707) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1cccc(c1)CSCc1ccccc1(11708) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)
    [c]1ccc(cc1)CSCc1ccccc1(11709) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34)

After model enlargement:
    The model core has 399 species and 6767 reactions
    The model edge has 11314 species and 43281 reactions

Saving current model core to Chemkin file...
Chemkin file contains 6767 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 6767 reactions.
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 01:20:19:56
    Memory used: 1657.63 MB

Conducting simulation of reaction system 1...
At time 1.0000e-01 s, species [CH](SCc1ccccc1)c1ccccc1(11570) exceeded the minimum rate for moving to model core
    Characteristic rate: 7.9141e+03 mol/m^3*s
    [CH] (SCc1ccccc1)c1ccccc1(11570) rate: 8.1752e+02 mol/m^3*s (0.1033)
    DBDS(1) conversion: 0.5313
At time 1.0000e-01 s, species [CH](SCc1ccccc1)c1ccccc1(11570) exceeded the minimum rate for simulation interruption
    Characteristic rate: 7.9141e+03 mol/m^3*s
    [CH](SCc1ccccc1)c1ccccc1(11570) rate: 8.1752e+02 mol/m^3*s (0.1033)
    DBDS(1) conversion: 0.5313

Adding species [CH] (SCc1ccccc1)c1ccccc1(11570) to model core
Generating kinetics for new reactions...

Summary of Model Enlargement
---------------------------------
Added 1 new core species
[CH] (SCc1ccccc1)c1ccccc1(11570)
Created 0 new edge species
Moved 1 reactions from edge to core
[CH]1C=CC=CC1=CSCc1ccccc1(271) + c1ccc(cc1)CSCc1ccccc1(34) <=> [CH] (SCc1ccccc1)c1ccccc1(11570) + c1ccc(cc1)CSCc1ccccc1(34)
Added 0 new core reactions
Created 0 new edge reactions

After model enlargement:
    The model core has 400 species and 6768 reactions
    The model edge has 11313 species and 43280 reactions

At time 1.0662e+00 s, reached target termination conversion: 0.800000 of DBDS(1)
    DBDS(1) conversion: 0.8001

The Summary of Model Enlargement for these two steps shows that the exact same species is added twice in a row (in this model the species had been added many many times before this as well). In fact, looking at the Summary of Secondary Model Edge Enlargement shows that the exact same reactions are considered twice in a row.

I believe the issue has to do with the ability of the resonance isomers to be recognized. Since the species in the core is not recognized to be the same as the newly generated edge species, the edge species and the associated identical reactions are added to the core in fault.

I am not sure how adding the species to a thermo library would affect the resonance isomer generation/recognition... it seems like it shouldn't. If anyone has any ideas I would be grateful! Or perhaps in the short term if you know a sneaky way to attach a thermo value to a species without sticking it in a library (maybe a very very specific branch in a thermo tree?)

Thanks!

**Comment by alongd** [comment]
Could you verify in the species dictionary (in the Chemkin folder) that '[CH] (SCc1ccccc1)c1ccccc1(11562)' and '[CH] (SCc1ccccc1)c1ccccc1(11570)' have identical definitions?

**Comment by alongd** [comment]
And if all these species are indeed identical, and you believe that they are unimportant for your model, you may want to forbid them (add the AdjList from the dictionary to forbiddenStructures.py in RMG-database\input). 
As you said, this only works as a temp patch, and the problem might return for a different species...

**Comment by rwest** [comment]
It could be that the resonance isomorphism bug was always there and adding there thermo library entry just made it more likely for these species to enter the core. 

It would be helpful to find the chemgraphs for these species from your dictionary to help someone debug the isomorphism. If RMG thinks they're different then probably they have different chemgraphs although clearly RDKit thinks they have the same SMILES. (It could also be a SMILES generation bug)

**Comment by rgillis8** [comment]
Actually this species was added to the mechanism about a 100 times and I just showed the final two for brevity. Apparently I stopped the simulation before S(11570) was added to the chemkin files so I will show the adjacency lists for S(11562) and S(11554) which are also identical species added in identical enlarge steps.

S(11554)
multiplicity 2
1  C u0 p0 c0 {2,S} {15,S} {16,S} {17,S}
2  C u0 p0 c0 {1,S} {4,D} {5,S}
3  C u0 p0 c0 {6,D} {7,S} {14,S}
4  C u0 p0 c0 {2,D} {11,S} {18,S}
5  C u0 p0 c0 {2,S} {12,D} {19,S}
6  C u0 p0 c0 {3,D} {8,S} {20,S}
7  C u0 p0 c0 {3,S} {9,D} {21,S}
8  C u0 p0 c0 {6,S} {10,D} {22,S}
9  C u0 p0 c0 {7,D} {10,S} {23,S}
10 C u0 p0 c0 {8,D} {9,S} {24,S}
11 C u0 p0 c0 {4,S} {13,D} {25,S}
12 C u0 p0 c0 {5,D} {13,S} {26,S}
13 C u0 p0 c0 {11,D} {12,S} {27,S}
14 C u1 p0 c0 {3,S} {15,S} {28,S}
15 S u0 p2 c0 {1,S} {14,S}
16 H u0 p0 c0 {1,S}
17 H u0 p0 c0 {1,S}
18 H u0 p0 c0 {4,S}
19 H u0 p0 c0 {5,S}
20 H u0 p0 c0 {6,S}
21 H u0 p0 c0 {7,S}
22 H u0 p0 c0 {8,S}
23 H u0 p0 c0 {9,S}
24 H u0 p0 c0 {10,S}
25 H u0 p0 c0 {11,S}
26 H u0 p0 c0 {12,S}
27 H u0 p0 c0 {13,S}
28 H u0 p0 c0 {14,S}

S(11562)
multiplicity 2
1  C u0 p0 c0 {2,S} {15,S} {16,S} {17,S}
2  C u0 p0 c0 {1,S} {4,D} {5,S}
3  C u0 p0 c0 {6,D} {7,S} {14,S}
4  C u0 p0 c0 {2,D} {11,S} {18,S}
5  C u0 p0 c0 {2,S} {12,D} {19,S}
6  C u0 p0 c0 {3,D} {8,S} {20,S}
7  C u0 p0 c0 {3,S} {9,D} {21,S}
8  C u0 p0 c0 {6,S} {10,D} {22,S}
9  C u0 p0 c0 {7,D} {10,S} {23,S}
10 C u0 p0 c0 {8,D} {9,S} {24,S}
11 C u0 p0 c0 {4,S} {13,D} {25,S}
12 C u0 p0 c0 {5,D} {13,S} {26,S}
13 C u0 p0 c0 {11,D} {12,S} {27,S}
14 C u1 p0 c0 {3,S} {15,S} {28,S}
15 S u0 p2 c0 {1,S} {14,S}
16 H u0 p0 c0 {1,S}
17 H u0 p0 c0 {1,S}
18 H u0 p0 c0 {4,S}
19 H u0 p0 c0 {5,S}
20 H u0 p0 c0 {6,S}
21 H u0 p0 c0 {7,S}
22 H u0 p0 c0 {8,S}
23 H u0 p0 c0 {9,S}
24 H u0 p0 c0 {10,S}
25 H u0 p0 c0 {11,S}.
26 H u0 p0 c0 {12,S}
27 H u0 p0 c0 {13,S}
28 H u0 p0 c0 {14,S} 

I can also confirm that even without the modified thermo value in the library the species enters the core without duplications albeit with a slightly different adjacency list...

1  C u0 p0 c0 {2,S} {15,S} {16,S} {17,S}
2  C u0 p0 c0 {1,S} {4,B} {5,B}
3  C u0 p0 c0 {6,B} {7,B} {14,S}
4  C u0 p0 c0 {2,B} {11,B} {22,S}
5  C u0 p0 c0 {2,B} {12,B} {23,S}
6  C u0 p0 c0 {3,B} {8,B} {18,S}
7  C u0 p0 c0 {3,B} {9,B} {19,S}
8  C u0 p0 c0 {6,B} {10,B} {20,S}
9  C u0 p0 c0 {7,B} {10,B} {21,S}
10 C u0 p0 c0 {8,B} {9,B} {24,S}
11 C u0 p0 c0 {4,B} {13,B} {25,S}
12 C u0 p0 c0 {5,B} {13,B} {26,S}
13 C u0 p0 c0 {11,B} {12,B} {27,S}
14 C u1 p0 c0 {3,S} {15,S} {28,S}
15 S u0 p2 c0 {1,S} {14,S}
16 H u0 p0 c0 {1,S}
17 H u0 p0 c0 {1,S}
18 H u0 p0 c0 {6,S}
19 H u0 p0 c0 {7,S}
20 H u0 p0 c0 {8,S}
21 H u0 p0 c0 {9,S}
22 H u0 p0 c0 {4,S}
23 H u0 p0 c0 {5,S}
24 H u0 p0 c0 {10,S}
25 H u0 p0 c0 {11,S}
26 H u0 p0 c0 {12,S}
27 H u0 p0 c0 {13,S}
28 H u0 p0 c0 {14,S}

Note that the benzene bonds are designated by B labels rather than the alternating S and D labels. Maybe this would affect an isomorphism check.

**Comment by rgillis8** [comment]
Another update. When I relabeled the bonds in the relevant species in the thermo library with B labels rather than alternating S and D labels the redundant species error disappeared. I'll keep looking into why this would make a difference.

**Comment by mliu49** [comment]
This might be related to one of the previous problems you discussed with me. I forgot the exact context, but the ordering of molecules within the species object was affecting the RMG job. Estimating thermo using group additivity reorders the molecule objects based on thermo, but retrieving thermo from a library does not. Therefore, for aromatic species, the aromatic resonance structure will almost always end up first in the list when using group additivity (due to aromatic stabilization), but the kekulized form will end up first in the list when using libraries (because we create kekulized adjlists by default).

I gave you a small patch to fix your previous problem, which put the resonance structure which matched the library entry first in the list of molecules. Assuming you're still using that, it would explain why using B labels in your library entry eliminates the error, the same as just using group additivity. If the aromatic form of the molecule is first in the list, then it works fine, but if the kekulized form is first, then the error appears.

It seems that the isomorphism check against existing species that is done before creating a new species is failing somehow. However, I'm not sure why that is dependent on the order of molecule objects.

**Comment by KEHANG** [comment]
@mliu49 this is a related issue #643 fixed by [some patch](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/644) in `checkForExistingSpecies` in case you are not aware of that. Maybe your patch has conflicts with the old patch?

**Comment by rgillis8** [comment]
I originally thought like you Kehang, but the problem persisted whether Max's patch was used or not.

Although per Max's comment I have not checked whether switching the bond labels would work if Max's patch was not present. I have only tested it when Max's patch was present.

**Comment by mliu49** [comment]
Ah, I was just looking at that fix. I remember seeing it, but had forgotten about it. I don't think it should conflict, since I modified `getThermoDataFromLibrary()` so the it would place the matched structure first in the molecule list.

However, `generateAromaticResonanceIsomers()` can give different results depending on which resonance structure is provided, so we might still mis-identify molecules as being different when they are actually the same.

@rgillis8, you could try checking out the resonance branch on official, to see if the improvements to `generateAromaticResonanceIsomers()` fix the error. However, it might have other effects on your model, besides potentially fixing this error, since your model has a lot of aromatic species that would be affected by the changes to resonance structures.

**Comment by mliu49** [comment]
I figured out what the problem is! I'm also very surprised that we haven't encountered this more often. Actually, we probably do encounter it, but don't notice because it won't cause an error most of the time. See #850 for the fix.

Suppose we have a radical species with two resonance structures, A and B, due to radical delocalization.

Process:
1. By reacting core species, we generate a new molecule A, which is sent to `makeNewSpecies`. ([code](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L282))
2. First, we use`checkForExistingSpecies` to run isomorphism against existing species (resonance structures have already been generated for existing species).
3. Nothing matches, so we make a new Species object using molecule A.
4. We run `generateResonanceIsomers`, so the species now has both A and B as molecules.
5. We generate thermo data for the species.
    1. We check libraries and don't find an exact match.
    2. We use HBI with saturated thermo from libraries. ([code](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/thermo.py#L1060))
        1. A and B become different species when saturated!
        2. The saturated B is in a library, but the saturated A is not, so we get 1 thermo result.
        3. We sort the thermo results by H298 (no effect, since there's only 1 result).
        4. We sort the molecule list by thermo, but we use a list comprehension based on the list of thermo results, so the molecule list only contains B now!
6. We add the species to the main species dictionary (with molecule B only).
7. A few iterations later, we generate molecule A again.
8. We use `checkForExistingSpecies`, but we don't find a match because only molecule B exists.
9. Go to Step 3, repeat ad infinitum...

**Comment by KEHANG** [comment]
closed by #850

**Comment by rwest** [comment]
Well done @mliu49 figuring this out! The explanation makes perfect sense, but was by no means obvious a priori. 
I think this is an important enough bug fix that we should make a release with a minor version number bump and push new binaries to anaconda. Perhaps to coincide with the new year?  There have been a few other fixes since the last release too. Since anaconda is so easy, very few users (excluding developers) compile from source.

**Comment by KEHANG** [comment]
Sure, I'll start preparing the new year release:D

**Comment by rwest** [comment]
@KEHANG how's that new year release coming? Oh, and 恭喜發財 😉

**Comment by KEHANG** [comment]
@rwest haha you too!! I guess it's coming soon with some pre-planned PRs that got some delay...
