### ISSUE TITLE
Cantherm not properly loading Gaussian files for TS's anymore

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#848]
Using the latest  version of the RMG-Py master branch (commit 65c8cc4) I can no longer run certain Cantherm jobs that were fine before. Specifically, I get the following error if the Cantherm job contains a transition state that  references a Gaussian file:

Traceback (most recent call last):
  File "/home/zjburas/RMG-Py/cantherm.py", line 61, in <module>
    cantherm.execute()
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/main.py", line 237, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/statmech.py", line 180, in execute
    self.load()
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/statmech.py", line 226, in load
    self.species.props['elementCounts'] = atoms
AttributeError: 'rmgpy.species.TransitionState' object has no attribute 'props'

So it seems that the transition state is not being properly loaded from the Gaussian file. If I go back to the RMG-Py master branch of about a month ago  (commit cef5c30), then the same Cantherm job runs just fine. So it must have been a recent change that caused this bug, but I'm not sure which out of the many commits that have been merged over the last month.

**Comment by nyee** [comment]
I haven't fully fleshed out the problem, but it's definitely commit c57a9654401a301e70f85352680eaaca2c6f519 that is causing the issue as that's where the line that the error takes place on was added. 

It looks like @mliu49 added a line to save the atoms of the species so that we could use pre-existing code to write a proper chemkin thermo entry. For some reason from the error you listed out, it is trying to apply that line of code to a transition state, which doesn't necessarily have (or need) all the atoms listed.

**Comment by KEHANG** [comment]
@zjburas can you use [this branch (dynamic_attr)](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/dynamic_attr) to see it can resolve the issue?

**Comment by zjburas** [comment]
@KEHANG I get the same error using the dynamic_attr branch. You should be able to replicate the error if you try running any Cantherm job with a transition state that references a  Gaussian file (unfortunately none of the RMG-Py examples fit this criteria).

**Comment by rwest** [comment]
We should add tests that catch this.

**Comment by KEHANG** [comment]
@zjburas you are right, I just updated the branch (`dynamic_attr`) again, this time should be working.

Note: it's force-pushed so you might want to first delete the previous `dynamic_attr` branch

**Comment by zjburas** [comment]
@KEHANG Using that branch I can now run a P-dep job again, but still can't do a thermo job. If there is a thermo() block for any of the species, I get the following error:

 File "/home/zjburas/RMG-Py/cantherm.py", line 61, in <module>
    cantherm.execute()
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/main.py", line 237, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/thermo.py", line 74, in execute
    self.save(outputFile)
  File "/home/zjburas/RMG-Py/rmgpy/cantherm/thermo.py", line 139, in save
    elementCounts = self.elementCounts
AttributeError: ThermoJob instance has no attribute 'elementCounts'

**Comment by KEHANG** [comment]
final try: this branch [TS_props](https://github.com/ReactionMechanismGenerator/RMG-Py/tree/TS_props). You need to re-make it by running `make clean` and `make` before testing on your examples. We can discuss more on Monday if it still has further issues.

**Comment by mliu49** [comment]
Thanks @KEHANG for solving this. This issue was that I was saving the element count under the the `props` attribute of `Molecule()`, but failed to realize that Cantherm also uses the `TransitionState()` class, which does not have the `props` attribute. I did not catch this because the jobs in the example folder did not encounter this issue.

While looking at this, I discovered another potential error where a thermo job will fail due to no elementCounts if a statmech job was not run prior. I will work on a fix for that, and combine it with this fix for pulling into master. I'll also try to come up with some unit tests.

**Comment by zjburas** [comment]
@KEHANG Using the TS_props branch I can run both P-dep and Thermo jobs again. Thanks for the fast fix.

**Comment by mliu49** [comment]
Question: Would users typically request thermo for transition states?

If not, then there may not be any point in saving element counts when we encounter a TransitionState object instead of a Species object.

**Comment by KEHANG** [comment]
@mliu49 I usually don't calculate thermo for TS...

**Comment by mliu49** [comment]
Actually, my question can be ignored. It's not possible to calculate thermo for a transition state in Cantherm. :smiley:
